/**
 * FontAwesome Icons Utility
 * Centralized icon imports for consistent usage across the app
 */
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faDashboard,
  faCog,
  faPlay,
  faProjectDiagram,
  faUser,
  faSearch,
  faBell,
  faComment,
  faBars,
  faChartBar,
  faCheckCircle,
  faExclamationTriangle,
  faClock,
  faArrowTrendUp,
  faArrowTrendDown,
  faEye,
  faDownload,
  faStar,
  faStarHalfStroke,
  faPlus,
  faEdit,
  faTrash,
  faChevronDown,
  faExchangeAlt,
  faShieldAlt,
  faFileDownload,
  faFilter,
  faTimes,
} from '@fortawesome/free-solid-svg-icons';

// Export icon components for easy use
export const Icons = {
  Dashboard: () => <FontAwesomeIcon icon={faDashboard} />,
  Settings: () => <FontAwesomeIcon icon={faCog} />,
  Play: () => <FontAwesomeIcon icon={faPlay} />,
  Pipeline: () => <FontAwesomeIcon icon={faProjectDiagram} />,
  User: () => <FontAwesomeIcon icon={faUser} />,
  Search: () => <FontAwesomeIcon icon={faSearch} />,
  Notifications: () => <FontAwesomeIcon icon={faBell} />,
  Chat: () => <FontAwesomeIcon icon={faComment} />,
  Menu: () => <FontAwesomeIcon icon={faBars} />,
  Chart: () => <FontAwesomeIcon icon={faChartBar} />,
  CheckCircle: () => <FontAwesomeIcon icon={faCheckCircle} />,
  Warning: () => <FontAwesomeIcon icon={faExclamationTriangle} />,
  Clock: () => <FontAwesomeIcon icon={faClock} />,
  TrendingUp: () => <FontAwesomeIcon icon={faArrowTrendUp} />,
  TrendingDown: () => <FontAwesomeIcon icon={faArrowTrendDown} />,
  Eye: () => <FontAwesomeIcon icon={faEye} />,
  Download: () => <FontAwesomeIcon icon={faDownload} />,
  Star: () => <FontAwesomeIcon icon={faStar} />,
  StarBorder: () => <FontAwesomeIcon icon={faStarHalfStroke} />,
  Add: () => <FontAwesomeIcon icon={faPlus} />,
  Edit: () => <FontAwesomeIcon icon={faEdit} />,
  Delete: () => <FontAwesomeIcon icon={faTrash} />,
  ExpandMore: () => <FontAwesomeIcon icon={faChevronDown} />,
  Compare: () => <FontAwesomeIcon icon={faExchangeAlt} />,
  Shield: () => <FontAwesomeIcon icon={faShieldAlt} />,
  FileDownload: () => <FontAwesomeIcon icon={faFileDownload} />,
  Filter: () => <FontAwesomeIcon icon={faFilter} />,
  Close: () => <FontAwesomeIcon icon={faTimes} />,
};

// Export raw icons for direct use with FontAwesomeIcon component
export const IconNames = {
  faDashboard,
  faCog,
  faPlay,
  faProjectDiagram,
  faUser,
  faSearch,
  faBell,
  faComment,
  faBars,
  faChartBar,
  faCheckCircle,
  faExclamationTriangle,
  faClock,
  faArrowTrendUp,
  faArrowTrendDown,
  faEye,
  faDownload,
  faStar,
  faStarHalfStroke,
  faPlus,
  faEdit,
  faTrash,
  faChevronDown,
  faExchangeAlt,
  faShieldAlt,
  faFileDownload,
  faFilter,
  faTimes,
};
